config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks'}
  root to: "questions#index"


  resources :questions do
    resources :answers, shallow: true
    resources :comments, only: [:new, :create]
    post :vote_up, on: :member
    post :vote_down, on: :member
    delete :cancel_vote, on: :member
  end

  resources :answers, only: [] do
    resources :comments, only: [:new, :create]
    post :vote_up, on: :member
    post :vote_down, on: :member
    delete :cancel_vote, on: :member
  end

  resources :attachments, only: [:destroy]

  namespace :api do
    namespace :v1 do
      resources :profiles do
        get :me, on: :collection
        get :others, on: :collection
      end

      resources :questions do
        resources :answers, shallow: true
      end
    end
  end


end

app/models/question.rb
class Question < ActiveRecord::Base
  include Votable
  include Attachable
  has_many :answers, dependent: :destroy

  has_many :comments, as: :commentable, dependent: :destroy

  belongs_to :user

  validates :body, :title, :user_id, presence: true
  validates :title, length: {maximum: 200}




end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController



  authorize_resource



  def index
    @questions = Question.all
    render json: @questions
  end

  def show
    @question = Question.find(params[:id])
    render json: @question
  end

  def create
    @question = Question.new(question_params)
    @question.user = current_resource_owner
    if @question.save
      render json: @question
    else
      render json: {errors: @question.errors.full_messages}, status: :unprocessable_entity
    end
  end

  private
  def question_params
    params.require(:question).permit(:title, :body)
  end


end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include ControllerVotable


  before_action :authenticate_user!, only: [:new, :edit, :create, :destroy, :update]
  before_action :load_question, only: [:show, :edit, :update, :destroy]
 # before_action :check_edit_rights, only: [:edit, :destroy]

  authorize_resource

  def index
    @questions = Question.all
  end

  def show
    @answer = Answer.new
    @attachment = @question.attachments.new
    @answer_attachment = @answer.attachments.new
  end

  def new
    @question = Question.new
    @attachment = @question.attachments.new
  end

  def edit
  end

  def create
    @question = Question.new(question_params)
    @question.user = current_user
    if @question.save
      PrivatePub.publish_to "/questions", new_question: @question
      redirect_to @question
    else
      @question.attachments = [Attachment.new]
      render :new
    end
  end

  def update
    respond_to do |format|
      format.js do
        @has_rights = false
        @signed_in = false
        if user_signed_in?
          @signed_in = true
          if current_user.can_edit?(@question)
            @has_rights = true
            @question.update(question_params)
          end
        end
      end

      format.json do
        case
          when !user_signed_in?
            render json: {}, status: :unauthorized
          when !current_user.can_edit?(@question)
            render json: {}, status: :forbidden
          when @question.update(question_params)
            render json: @question
          else
            render json: {errors: @question.errors.full_messages}, status: :unprocessable_entity
        end
      end
    end

   # if @question.update(question_params)
   #   redirect_to @question
   # else
   #   render :edit
   #  end
  end

  def destroy
    @question.destroy
    redirect_to questions_path
  end




  private
  def load_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body, attachments_attributes: [:file])
  end

  # def check_edit_rights
  #   unless user_signed_in? && current_user.can_edit?(@question)
  #     redirect_to @question, notice: 'You don\'t have rights to perform this action.'
  #   end
  # end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.slim
.question-errors
  - question.errors.full_messages.each do |message|
    p= message

= form_for question, remote: (!question.new_record?), format: (question.new_record? ? :html : :json) do |f|
  = f.label :title
  = f.text_field :title
  = f.label :body, 'Text'
  = f.text_field :body
  - if question.new_record?
    p Attachments
    p
      = f.fields_for :attachments do |a|
        = link_to_add_association 'Add file', f, :attachments, partial: 'attachments/attachment_fields'

  = f.submit (question.new_record? ? 'Create' : 'Save')

app/views/questions/_question.html.slim
p= link_to question.title, question

app/views/questions/edit.html.slim
h1 New question

= render 'form', question: @question

app/views/questions/index.html.slim
h1 Questions
.questions
  = render @questions


= link_to 'Ask question', new_question_path

= subscribe_to "/questions"

app/views/questions/new.html.slim
h1 New question

= render 'form', question: @question

app/views/questions/show.html.slim
#content.read_question_section
  h1= @question.title
  p= @question.body
  = render @question.attachments
  .question_comments_section
    - unless @question.comments.empty?
      strong Comments:
      em
        = render @question.comments
    - if can?(:create, Comment)
      em
        = link_to 'Add comment to question', new_question_comment_path(@question)


.write_question_section.hidden
  = render 'form', question: @question
  = link_to "Cancel", '#', id: 'cancel_edit_question_link'
.read_question_section
  - if can?(:update, @question) || can?(:destroy, @question)
    h3 Actions:
    ul
      - if can?(:update, @question)
        li= link_to 'Edit', '#', id: 'edit_question_link'
      - if can?(:destroy, @question)
        li= link_to 'Delete', @question, method: :delete
      - if can?(:vote_up, @question)
        p
          em= link_to 'Upvote question', question_path(@question)+'/vote_up', method: :post, class: 'upvote_question_link', remote: true, format: :json
      - if can?(:vote_down, @question)
        p
          em= link_to 'Downvote question', question_path(@question)+'/vote_down', method: :post, class: 'downvote_question_link', remote: true, format: :json
      - if can?(:cancel_vote, @question)
        p
          em= link_to 'Cancel vote on question', question_path(@question)+'/cancel_vote', method: :delete, class: 'cancelvote_question_link', remote: true, format: :json
      p Rating: #{@question.votes_sum}

h2 Answers
.answers
  = render @question.answers
-if can?(:create, Answer)
  .new_answer
    = render 'answers/form', question: @question, answer: @answer

= subscribe_to "/questions/#{@question.id}/answers"

app/views/questions/update.js.erb
$('.question-errors').empty();

<% @question.errors.full_messages.each do |message| %>
$('.question-errors').append('<p><%= j message %></p>');
<% end %>

<% if @question.errors.empty? %>
$('.read_question_section#content').html("<h1><%= @question.title %></h1><p><%= @question.body %></p>");
questionReadMode();
<% end %>