config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks'}
  root to: "questions#index"


  resources :questions do
    resources :answers, shallow: true
    resources :comments, only: [:new, :create]
    post :vote_up, on: :member
    post :vote_down, on: :member
    delete :cancel_vote, on: :member
  end

  resources :answers, only: [] do
    resources :comments, only: [:new, :create]
    post :vote_up, on: :member
    post :vote_down, on: :member
    delete :cancel_vote, on: :member
  end

  resources :attachments, only: [:destroy]

  namespace :api do
    namespace :v1 do
      resources :profiles do
        get :me, on: :collection
        get :others, on: :collection
      end

      resources :questions do
        resources :answers, shallow: true
      end
    end
  end


end

app/models/answer.rb
class Answer < ActiveRecord::Base
  include Votable
  include Attachable
  belongs_to :question
  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy
  validates :body, :question_id, :user_id, presence: true

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include ControllerVotable


  before_action :authenticate_user!, only: [:create,:update,:destroy]
  before_action :load_answer, only: [:update, :destroy]
  #before_action :check_edit_rights, only: [:edit]

  authorize_resource



  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.new(answer_params)
    @answer.user = current_user
    @answer.save
  end


  def update
    respond_to do |format|
      # format.js do
      #   @has_rights = false
      #   @signed_in = false
      #   if user_signed_in?
      #      @signed_in = true
      #      if current_user.can_edit?(@answer)
      #        @has_rights = true
      #        @answer.update(answer_params)
      #      end
      #   end
      # end

      format.json do
        case
          when @answer.update(answer_params)
            render json: @answer
          else
            render json: {errors: @answer.errors.full_messages}, status: :unprocessable_entity
        end
      end
    end
  end

  def destroy
    @answer.destroy
  end





  private
  def answer_params
    params.require(:answer).permit(:body,:question_id, attachments_attributes: [:file])
  end

  def load_answer
    @answer = Answer.find(params[:id])
  end

  # def check_edit_rights
  #   unless user_signed_in? && current_user.can_edit?(@answer)
  #     redirect_to @answer.question, notice: 'You don\'t have rights to perform this action.'
  #   end
  # end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController

  authorize_resource



  def index
    @question = Question.find(params[:question_id])
    render json: @question.answers, each_serializer: ::ShortAnswerSerializer
  end

  def show
    @answer = Answer.find(params[:id])
    render json: @answer
  end


end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
= div_for(answer, class: "read_answer_section") do |answer|
  p= answer.body
  = render answer.attachments
  .answer_comments_section
    - unless answer.comments.empty?
      strong Comments:
      em
        = render answer.comments
    -if can?(:create, Comment)
      em
        = link_to 'Add comment to answer', new_answer_comment_path(answer)
  br
  -if can?(:update, answer)
    p
      em= link_to 'Edit answer', '#', class: 'edit_answer_link'
  -if can?(:destroy, answer)
    p
      em= link_to 'Delete answer', answer, method: :delete, remote: true
  -if can?(:vote_up, answer)
    p
      em= link_to 'Upvote answer', answer_path(answer)+'/vote_up', method: :post, class: 'upvote_answer_link', remote: true, format: :json
  -if can?(:vote_down, answer)
    p
      em= link_to 'Downvote answer', answer_path(answer)+'/vote_down', method: :post, class: 'downvote_answer_link', remote: true, format: :json
  -if can?(:cancel_vote, answer)
    p
      em= link_to 'Cancel vote on answer', answer_path(answer)+'/cancel_vote', method: :delete, class: 'cancelvote_answer_link', remote: true, format: :json
  p Answer rating: #{answer.votes_sum}
= div_for(answer, class: "write_answer_section hidden") do |answer|
    = render 'answers/form', answer: answer, question: answer.question
    p
      em= link_to 'Cancel', '#', class: 'cancel_edit_answer_link'
br
br

app/views/answers/_form.html.slim
.answer-errors
  - answer.errors.full_messages.each do |message|
    p= message

= form_for (answer.new_record? ? [question, answer] : answer ), remote: true, format: (answer.new_record? ? :js : :json) do |f|
  = f.label :body, 'Your answer:'
  = f.text_field :body
  - if answer.new_record?
    p Attachments
    p= f.fields_for :attachments do |a|
      = link_to_add_association 'Add file', f, :attachments, partial: 'attachments/attachment_fields'
  = f.submit (answer.new_record? ? "Post answer" : "Save")

app/views/answers/create.js.erb
$('.answer-errors').empty();
$('.nested_attach_fields').remove();
<% @answer.errors.full_messages.each do |message| %>
  $('.answer-errors').append('<p><%= j message %></p>');
<% end %>

<% if @answer.errors.empty? %>
  <% publish_to "/questions/#{@answer.question_id}/answers" do %>
    $('.answers').append('<%= j render @answer %>');
    $('.new_answer input#answer_body').val("");
    $('.new_answer input[type="file"]').val("");
  <% end %>
<% end %>

app/views/answers/destroy.js.erb
$('answer-errors').empty();

<% @answer.errors.full_messages.each do |message| %>
  $('.answer-errors').append('<%= j message %>');
<% end %>

<% if @answer.errors.empty? %>
  $(' <%= '.answer#answer_' + @answer.id.to_s %>').remove();
<% end %>

app/views/answers/edit.html.slim
h1 Edit answer
= render 'form', answer: @answer, question: @answer.question

app/views/answers/update.js.erb
$('.answer-errors').empty();

<% @answer.errors.full_messages.each do |message| %>
$('.answer-errors').append('<p><%= j message %></p>');
<% end %>

<% if @answer.errors.empty? %>
  $(' <%= '.answer.read_answer_section#answer_' + @answer.id.to_s %>').children().first().replaceWith("<p><%= j @answer.body %></p>");
  answerReadMode();
<% end %>